# Arrays

### 1. Array module

In [2]:
import array

In [12]:
### creation
arr1 = array.array('i', [10, 20, 30, 20, 50])
print(arr1)

array('i', [10, 20, 30, 20, 50])


In [13]:
arr2 = array.array('i', [60, 70, 80])
print(arr2)

array('i', [60, 70, 80])


In [14]:
### access
arr1[2]

30

In [16]:
arr1[3]

20

In [18]:
### traversal
for element in arr1:
    print(element)

10
20
30
20
50


In [20]:
for element in arr1:
    print(element, end= " ")

10 20 30 20 50 

In [26]:
### insertion
arr1.insert(3, 35)
print(arr1)

array('i', [10, 20, 35, 35, 35, 20, 50])


In [29]:
### deletion
arr1.remove(30)
print(arr1)

ValueError: array.remove(x): x not in array

In [31]:
### updation
arr1[2] = 30
print(arr1)

array('i', [10, 20, 30, 35, 35, 20, 50])


In [32]:
### sorting
arr3 = array.array('i', [4, 7, 3, 9, 2, 6])
sorted(arr3)

[2, 3, 4, 6, 7, 9]

In [33]:
### merging
arr4 = arr1 + arr2
print(arr4)

array('i', [10, 20, 30, 35, 35, 20, 50, 60, 70, 80])


In [ ]:
 ### splitting
 ix = int(len(arr4)/ 2)
 print(arr4[:ix])
print(arr4[ix:])


array('i', [10, 20, 30, 35, 35])
array('i', [20, 50, 60, 70, 80])


## 2. Numpy

In [35]:
import numpy as np


In [36]:
### creation
np1 = np.array([10, 20, 30, 20, 50])
np2 = np.array([60, 70, 80])

In [37]:
### access
np1[0]

np.int64(10)

In [38]:
### traversal
for ele in np1:
    print(ele)

10
20
30
20
50


In [39]:
### insertion
np.insert(np1, 3, 35)

array([10, 20, 30, 35, 20, 50])

In [40]:
### deletion
np.delete(np1, 3)

array([10, 20, 30, 50])

In [41]:
### updation
np1[2] = 35
print(np1)

[10 20 35 20 50]


In [42]:
### sorting
np3 = np.array([5, 8, 4, 9, 1, 6])
np.sort(np3)

array([1, 4, 5, 6, 8, 9])

In [45]:
### merging
np3 = np.concatenate((np1, np2))
print(np3)

[10 20 35 20 50 60 70 80]


In [46]:
### splitting
split1, split2 = np.array_split(np3, 2)
print(split1, split2)

[10 20 35 20] [50 60 70 80]


### Vectorization

In [ ]:
np1 + 10 # add scalar to every element

array([20, 30, 45, 30, 60])

In [ ]:
np1 * 2 # multiply every element

array([ 20,  40,  70,  40, 100])

In [49]:
np3 = np.array([4, 5])
np4 = np.array([6, 7])
np3 / np4 # element-wise division

array([0.66666667, 0.71428571])